name: Deploy to Development

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: npm install parcel

      - name: Build Project
        run: npx parcel build src/index.html

      - name: Upload Artifact for Pages
        uses: actions/upload-artifact@v4
        with:
          name: github-pages
          path: ./dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
